### ISSUE TITLE
GFF3 parsing bug: parentless CDS/exon feature not recognized as transcript

### ISSUE THREAD

**Issue by afinit** [gpertea/stringtie#48] opened 2016-05-17 23:38 UTC
I've been using stringtie successfully for a while now. I just updated to the newest version, but now I'm getting the following error:

    Error: could not read reference annotation transcripts from GTF/GFF xam668_prokka.exon.gff3 - invalid file?

I have run an older version (which version I'm not sure at the moment) of `stringtie` successfully with this file just the other day, however the update seems to be checking something that I can't for the life of me figure out. Here are a few of the various versions of my gff file I have tried, the first one is the original and the one that worked with an older version of stringtie:

    Xam668_contig195        Prodigal:2.6    CDS     700     1398    .       -       0       ID=xam668_04238;gene=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein

    Xam668_contig195        Prodigal:2.6    exon    700     1398    .       -       0       ID=xam668_04238;gene_name=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein

    Xam668_contig195        Prodigal:2.6    mRNA    700     1398    .       -       0       ID=xam668_04238;gene=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein

    Xam668_contig195        Prodigal:2.6    CDS     700     1398    .       -       0       ID=xam668_04238;gene_name=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein

    Xam668_contig195        Prodigal:2.6    CDS     700     1398    .       -       0       ID=xam668_04238;gene=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein

    Xam668_contig195        Prodigal:2.6    CDS     700     1398    .       -       0       ID=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein

    Xam668_contig195        Prodigal:2.6    gene    700     1398    .       -       0       ID=xam668_04238;Name=xam668_04238

Based on experience with any number of programs that process gff files, including stringtie and cufflinks, each of these files follow the standards. Any help indicating what I should change to make this file fall in line with `stringtie`'s new standard would be great

**Comment by afinit** [comment] 2016-05-18 00:48
Since posting, I went back and tried a couple previous versions. The last version to work is v1.1.2 when I tried running v1.2.0, I got the same error as reported above. I guess I'll stick with the older version for now, but it would be nice to know what changed in the GFFReader that is causing stringtie to be inable to find transcripts in my gff files.

**Comment by gpertea** [comment] 2016-05-18 00:48
The example you've shown here seems to be just a single-exon transcript. The format seems to be GFF3-like but there are no well formed child features (exons/CDS) belonging to a transcript parent feature. Indeed I have tighten the requirements for GFF3 parsing in the last version so a parent transcript feature is now expected, with well defined child feature(s) (i.e. having a **Parent** attribute with the same value as the **ID** attribute of its parent). I did that because it was way too loose before, leading to confusion and loss of transcript data in some cases. All major annotation sources nowadays use either this kind of GFF3 format (with matching ID/Parent attribute values), or the older GTF format with all features using just ``transcript_id``.
Assuming that all tabs are where they should be (even though they look like spaces here), you could try a combination of the 3rd line followed by the 4th line as shown in your attempts, in order to represent this transcript, but make sure you replace ``ID=`` with ``Parent=`` in the CDS feature line, like this:
```
Xam668_contig195        Prodigal:2.6    mRNA    700     1398    .       -       .     ID=xam668_04238;gene=xam668_04238;inference=ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1;locus_tag=xam668_04238;product=partition protein
Xam668_contig195        Prodigal:2.6    CDS     700     1398    .       -       0     Parent=xam668_04238
```

There is some info (and a simple example) about the minimal GFF3 format expected by stringtie and other programs, that you might find helpful, on this page: http://ccb.jhu.edu/software/stringtie/gff.shtml#format

**Comment by afinit** [comment] 2016-05-18 00:56
I'm currently working with a bacterial genome, and since there aren't frequently any introns in these genes, I don't need parent lines. This file was created by a bacterial genome denovo annotation program called prokka. So are you saying that there is no way that I can run this new version without creating parent lines for my gff? Or are you saying that I can use the GTF format for one line genes?

**Comment by afinit** [comment] 2016-05-18 01:01
It seems a more informative error here would have addressed this issue. Would it be difficult to throw a more detailed warning or error describing what in particular is causing an issue? For instance `Error: missing Parent attribute`

**Comment by gpertea** [comment] 2016-05-18 01:13
Yes, in this case you might find it easier to use the GTF format instead, with just the CDS (or exon) features and transcript_id - but don't forget the double quotes for this format! It would look something like this:
```
Xam668_contig195        Prodigal:2.6    CDS   700     1398    .       -       0     transcript_id "xam668_04238"; gene_id "xam668_04238"; inference "ab initio prediction:Prodigal:2.6,similar to AA sequence:RefSeq:WP_007974205.1"; locus_tag "xam668_04238";product "partition protein"
```
Please keep in mind that stringtie does not care about any other attributes there, so if you really want to save space, just transcript_id would be enough.

A comment on this earlier statement:

> Based on experience with any number of programs that process gff files, including stringtie and cufflinks, each of these files follow the standards. 

I disagree, the GFF3 parser in cufflinks and the older stringtie version were simply allowing such malformed/incomplete GFF3 records but that does not mean that those records "follow the standards". I do remember that I allowed that because of some legacy GFF (2?) files, but since then GFF3 and GTF became well defined and widely adopted, so I withdraw support for those ancient files.

I am somewhat surprised that the GFF line with just the mRNA did not work for you, I guess I should've allowed that exception, which for bacterial genomes makes a lot of sense (or even just a childless ``gene`` feature should be accepted, as for bacteria gene=transcript=exon=CDS). I may tinker a bit with the code to allow such implied single-exon childless features again..

**Comment by gpertea** [comment] 2016-05-18 01:23
As a side note I find it intriguing that you're using something like StringTie, which is mainly a sophisticated *isoform* assembler/resolver, on bacterial genomes and transcripts. I guess you are using it mostly for the abundance estimation but I am pretty sure there are more suitable tools out there for doing this on prokaryotic genomes..

**Comment by gpertea** [comment] 2016-05-18 01:36
OK, it seems I was plain wrong in my assumption that matching ID/Parent values are somehow *required* by the GFF3 format, I just saw the Bacteriophage f1 example at  http://www.sequenceontology.org/gff3.shtml and it is exactly as you described it that prokka wrote it -- just a CDS with an ID attribute should be enough to represent the whole gene. I guess I've been focusing on multi-exon transcripts for so long, I forgot that such an GFF3 record is perfectly OK..

So I am going to mark this down as a GFF3 parsing issue (a regression bug!) that should be fixed in my code. Thank you for bring this problem to my attention..

**Comment by afinit** [comment] 2016-05-18 01:44
Thank you for addressing my issues. I'll use the older version of stringtie until I get around to writing a script to reformat my gff files.

**Comment by gpertea** [comment] 2016-06-09 01:51
This should have been fixed in an earlier commit, should make it into the next release.

**Closed by gpertea** 2016-06-09 01:51 UTC
Labels: bug
