### ISSUE TITLE
preDE.py stops at the second file 

### ISSUE THREAD

**Issue by AishMandya** [gpertea/stringtie#234] opened 2019-08-26 11:49 UTC
@tsznxx @nongbaoting @gpertea 
Hi I have modified the sample folder to 
label space file path
label space file path
but the error persists 
Each gtf file is inside a subdirectory of the ballgown directory generated by the stringtie -B -e 

$ prepDE.py -i sample_1st.txt
output:
0 A1_S1
1 A2_S2
Traceback (most recent call last):
  File "prepDE.py", line 257, in <module>
    geneDict[geneIDs[i]][s[0]]+=v[s[0]]
KeyError: 'A2_S2'
similar to issue #232

**Comment by lelesama** [comment] 2019-08-27 14:08
Hi,I have the same question ,do you have solved?

**Comment by AishMandya** [comment] 2019-08-27 14:17
No, not yet. IT seems to stop working at the second iteration, no matter which file it is. So it may be a glitch in the code or the way I have used stringtie to generate the gtf files. Also, I don't fully understand how the code works so it's definitely inconclusive

**Comment by lelesama** [comment] 2019-08-28 23:57
Hi,AishMandya,it actually  made me crazy  ！but when I use older version ,it works! maybe you can try,hope it will help you.

**Comment by SofiaZhangtj** [comment] 2019-10-04 07:52
Did you use the --merge during stringtie step?

**Comment by AishMandya** [comment] 2019-10-04 14:18
Hi,
Yes, i did use merge,  all --merge does is merge all the gtf files to give
the commonly hit genes, but no tpm info. The statistics is also relating to
the common genes found and not their tpm or log fold change.
I ended up writing a code for getting the tpm values and their averages
across samples and calculates the log fold change using the the common
genes output from --merge.
I don't think the method is too reliable because it's not recommended to do
any kind of DE On tpm values.
But string tie outputs unannotated genes (or sequences) as well, which may
be very useful.

Finally, i ended up doing most of my analysis with salmon, tximport and
edgeR/deSeq2

Thanks,
Aish

**Comment by SofiaZhangtj** [comment] 2019-10-05 03:35
Hi Aish,
Thank you for explaining these to me. I think I finally found my problem. This prepDE.py script is supposed to based on version 1.2, and now the software has been updated many times but the scripts have not. I changed my stringtie version from 2 to 1.3.3, then the script works.

**Comment by coreyscipione** [comment] 2019-10-05 22:34
Hi @SofiaZhangtj and @AishMandya , 
I am using stringtie 1.3.3 with the prepDE.py, to generate files for DESeq2 and I keep clogging up at the error:
Traceback (most recent call last):
  File "/cluster/home/cscipion/scripts/prepDE", line 257, in <module>
    geneDict[geneIDs[i]][s[0]]+=v[s[0]]
KeyError: 'B1pr_S13_L002'

Any thoughts? Maybe @gpertea can help.

**Comment by SofiaZhangtj** [comment] 2019-10-06 03:48
> Hi @SofiaZhangtj and @AishMandya ,
> I am using stringtie 1.3.3 with the prepDE.py, to generate files for DESeq2 and I keep clogging up at the error:
> Traceback (most recent call last):
> File "/cluster/home/cscipion/scripts/prepDE", line 257, in
> geneDict[geneIDs[i]][s[0]]+=v[s[0]]
> KeyError: 'B1pr_S13_L002'
> 
> I use have successfully used the sample 'B1pr_S13_L002' in several other comparisons, but this set of samples is rejecting it for some reason.
> 
> Any thoughts? Maybe @gpertea can help.

Hi,
I found that even the last version 1.3.6 works for me. I think met a same problem with yours at the beginning. That time I didn't use the "-e" parameter in string-tie.

**Comment by gpertea** [comment] 2019-10-06 04:23
I'll investigate the possibility that some changes in Stringtie v2 may have affected the compatibility with prepDE.py, but in the past there were a lot of "errors" alleged by users of prepDE.py which were mainly caused by an incorrect usage of the script. 
To reiterate and clarify:  prepDE.py can only be used on a set of stringtie GTF outputs if stringtie was run, for all those outputs: 
- with the **-e option** 
- with the **same file for the -G option**.

Also, make sure that **no other GTF files** (like the reference annotation file) are present in those sub-directories, only the stringtie output GTF files should be found there, as the default mode of operation for prepDE is to scan all the sub-directories there for .gtf files which are all expected to have been produced by stringtie by following the requirements above (**-e** option,  same **-G** file).

**Comment by SofiaZhangtj** [comment] 2019-10-07 03:08
@gpertea 
Hi Pertea,
Thank you for your reply. The output gtf files of stringtie v2 have different lines, but in previous vision it was the same. But the t_data.ctab files remain same as the older version. I think that's why prepDE.py doesn't work for the 2.0 version for my case. 


lines number of the older version (GTF file) (Two pairs of identical sequencing data )
![1](https://user-images.githubusercontent.com/49335842/66282619-99b4bf80-e8f2-11e9-94d6-3b39a33bff72.jpg)
![2](https://user-images.githubusercontent.com/49335842/66282628-9faaa080-e8f2-11e9-8020-97c4b490598c.jpeg)
lines number of the older version :
![3](https://user-images.githubusercontent.com/49335842/66282648-b51fca80-e8f2-11e9-808f-00b60178a95f.jpeg)
![4](https://user-images.githubusercontent.com/49335842/66282656-b8b35180-e8f2-11e9-831d-917464555b12.jpeg)

**Comment by coreyscipione** [comment] 2019-10-11 03:18
I am using the -e and -B option, and there is only one .gtf in the directory. 
The oddity is really that I have 23 samples (7 triplicates + 2 others). Samples 1-3 have been compared against 4-6, 7-9, 16-18 with no issues. When I compare 1-3 vs 10-12 is the only time I get the previously mentioned error. 
In this case I am sure everything is set up correctly, I am tempted to think that it’s a stringtie issue and not a syntax problem. Any further suggestions? Thank you all!

**Comment by gpertea** [comment] 2019-10-14 03:47
I've added some consistency checking to the prepDE.py script when reading the input data, it should catch some common usage errors. 
Could you please download the [latest prepDE.py script](https://raw.githubusercontent.com/gpertea/stringtie/master/prepDE.py), place it in your working directory, make sure it's executable and then run it again with the same parameters you used before but this time **add the -v option**, capturing the output in a file, with a command like this:

`./prepDE.py `  _(your parameters here)_ ` -v  2>&1  | tee prepDE.log`

(Use the link above to get this updated script, or you can also download the attached [prepDE.py.gz](https://github.com/gpertea/stringtie/files/3722825/prepDE.py.gz), copy it into your working directory,  gunzip it and make it executable, then make sure you run it with `./prepDE.py`) 

You can then show the prepDE.log here or email it to me.

**Comment by AishMandya** [comment] 2019-10-14 10:35
Thank you ! @gpertea/stringtie
<reply@reply.github.com>

**Comment by nourelislam** [comment] 2019-10-27 10:51
> I'll investigate the possibility that some changes in Stringtie v2 may have affected the compatibility with prepDE.py, but in the past there were a lot of "errors" alleged by users of prepDE.py which were mainly caused by an incorrect usage of the script.
> To reiterate and clarify: prepDE.py can only be used on a set of stringtie GTF outputs if stringtie was run, for all those outputs:
> 
> * with the **-e option**
> * with the **same file for the -G option**.
> 
> Also, make sure that **no other GTF files** (like the reference annotation file) are present in those sub-directories, only the stringtie output GTF files should be found there, as the default mode of operation for prepDE is to scan all the sub-directories there for .gtf files which are all expected to have been produced by stringtie by following the requirements above (**-e** option, same **-G** file).

Is it mandatory to use **-e option**?? As a matter of fact, I am working on detecting the novel splice sites so I should disregard **-e option**

**Comment by gpertea** [comment] 2019-10-29 21:05
This (the OP) seems to be the same issue with #232, so it should be fixed in v2.0.4 release.

**Closed by gpertea** 2019-10-29 21:05 UTC

**Comment by gpertea** [comment] 2019-10-29 21:10
Also same with #238, I'll leave only that issue open for a while, for user confirmation that the problem was fixed in v2.0.4

**Comment by nalcala** [comment] 2020-01-17 12:45
@gpertea I am all good now with the new versions, on my side you can close the issue. Thanks a lot!

**Comment by ElzaFosneca** [comment] 2023-01-26 18:32
> I've added some consistency checking to the prepDE.py script when reading the input data, it should catch some common usage errors. Could you please download the [latest prepDE.py script](https://raw.githubusercontent.com/gpertea/stringtie/master/prepDE.py), place it in your working directory, make sure it's executable and then run it again with the same parameters you used before but this time **add the -v option**, capturing the output in a file, with a command like this:
> 
> `./prepDE.py ` _(your parameters here)_ ` -v 2>&1 | tee prepDE.log`
> 
> (Use the link above to get this updated script, or you can also download the attached [prepDE.py.gz](https://github.com/gpertea/stringtie/files/3722825/prepDE.py.gz), copy it into your working directory, gunzip it and make it executable, then make sure you run it with `./prepDE.py`)
> 
> You can then show the prepDE.log here or email it to me.
Hi @gpertea,

I am running version v.2.2.1 and I'm getting the same error.

[prepDE.log](https://github.com/gpertea/stringtie/files/10512359/prepDE.log)

**Comment by RJEGR** [comment] 2023-03-17 15:33
Hi everyone,

Same error for StringTie v2.2.1, 

By using the prepDE.py version than @gpertea made the error remains,
 
`prepDE.py -i samples.txt  -v  2>&1  | tee prepDE.log`

>processing sample SRR8956796 from file /home/rvazquez/RNA_SEQ_ANALYSIS/ASSEMBLY/STRINGTIE/QUANTIFICATION/DENOVO_MODE/SRR8956796_eB_dir/SRR8956796_eB.gtf
>processing sample SRR8956797 from file /home/rvazquez/RNA_SEQ_ANALYSIS/ASSEMBLY/STRINGTIE/QUANTIFICATION/DENOVO_MODE/SRR8956797_eB_dir/SRR8956797_eB.gtf
Error: could not locate transcript MSTRG.31643.1 entry for sample SRR8956797
Traceback (most recent call last):
  File "/home/rvazquez/RNA_SEQ_ANALYSIS/stringtie/prepDE.py", line 284, in <module>
    geneDict.setdefault(geneIDs[i],{}) #gene_id
KeyError: 'MSTRG.31643.1'

**Comment by jubiology** [comment] 2023-05-04 08:51
I also encounter the same problems with all tested versions of Stringtie. When I use the prepDE.py3 script, it gives me a very weird gene count matrix, where samples 2-x show massive zero inflation while sample 1 looks normal. Also the last line does not look like expected: 

![image](https://user-images.githubusercontent.com/127126451/236155656-de1669ba-3ae0-4626-93d0-098adecfa297.png)

If anybody has any hints on how to solve this please let me know.
