### ISSUE TITLE
Does stringtie offer support for POWER architecture?

### ISSUE THREAD

**Issue by cbmckni** [gpertea/stringtie#138] opened 2017-08-05 15:41 UTC
Hello, 

I am developing a workflow on an IBM POWER8 server, and stringtie is used in one of the steps. I have tried installing from source code, however the software does not seem to be functioning correctly. Here is the input and output:

/home/cbmckni2/bin/stringtie-1.3.3b/stringtie /home/cbmckni2/bin/POWER8-GEM/Alignment/SRR1813870-accepted_hits.view.sorted -G /home/cbmckni2/bin/POWER8-GEM/Reference/chr21-gencode.v24.annotation.gff3 -eB -o ./SRR1813870.hisat2.StringTie.hits.bam.gtf -v

[08/05 11:39:38] Loading reference annotation (guides)..
GFF warning: merging adjacent/overlapping segments of ENST00000624847.1 on chr21 (6358555-6358574, 6358577-6358738)
GFF warning: merging adjacent/overlapping segments of ENST00000624847.1 on chr21 (6358555-6358738, 6358741-6359767)
GFF warning: merging adjacent/overlapping segments of ENST00000291525.11 on chr21 (42313485-42313493, 42313495-42313631)
GFF warning: merging adjacent/overlapping segments of ENST00000621064.1 on chr21 (44425670-44425711, 44425713-44425742)
GFF warning: merging adjacent/overlapping segments of ENST00000621064.1 on chr21 (44425670-44425742, 44425744-44425827)
GFF warning: merging adjacent/overlapping segments of ENST00000610622.4 on chr21 (44891809-44891935, 44891937-44891996)
GFF warning: merging adjacent/overlapping segments of ENST00000621201.4 on chr21 (46648458-46648538, 46648540-46648619)
GFF warning: merging adjacent/overlapping segments of ENST00000621201.4 on chr21 (46658745-46658798, 46658800-46659430)
[08/05 11:39:39] 2449 reference transcripts loaded.
Default stack size for threads: 8388608
[08/05 11:39:39]>bundle chr21:5011799-5017150(8) (1 guides) loaded, begins processing...
[08/05 11:39:39]^bundle chr21:5011799-5017150(8) done (1 processed potential transcripts).
[08/05 11:39:39]>bundle chr21:5018461-5244053(4619) (30 guides) loaded, begins processing...
Segmentation fault

Could y'all please help me figure out if this is user error or software error? 

Much appreciated, 

Cole

**Comment by cbmckni** [comment] 2017-08-05 15:44
By the way, I am running this on:
 Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-83-generic ppc64le)

ppc64le means 64-bit little endian

**Comment by gpertea** [comment] 2017-08-05 17:10
We don't have such systems around to test on, but the C++ code should work the same, especially since your system seems to have the same endianness and the same word size with our Intel x86_64 systems. Have you tried the same data set on such a regular Intel system and did it work there?
If that wasn't the case, I would rather suspect some unusual input configuration (alignments vs. reference transcripts). Is it possible to share the read alignments in that region (chr21:5018461-5244053) ? It would be good if you could extract those alignments using samtools and confirm that StringTie crashes on your ppc64le system only with that bundle of alignments as input (and the reference gff3 file), then share those alignments to us for testing/debugging. We would also need the chr21-gencode.v24.annotation.gff3 file, since you used -e option.

**Comment by cbmckni** [comment] 2017-08-05 17:28
Thank you for the quick response. I will get you everything you need at
some point today. I have not personally tested the data set on the intel
system, but one of my colleagues has with success.

**Comment by cbmckni** [comment] 2017-08-06 21:29
The select bundle of alignments and the reference file are in the .zip. I could not figure out how to run stringtie with just the select alignments as input, as there is no header. I apologize for the delay, I am an undergrad that recently got into the world of genomics. Still learning how to use the myriad of tools that are out there. Please let me know if you need anything else from me. Thank you for your help.

Cole 

[testfiles.zip](https://github.com/gpertea/stringtie/files/1203455/testfiles.zip)

**Comment by gpertea** [comment] 2017-08-25 17:31
The problem seems to be caused by the fact that on IBM Power8 systems the **char** type is **unsigned** by default, as opposed to Intel x86 architectures. Simply adding the compile flag `-fsigned-char` seems to fix this issue.

**Comment by gpertea** [comment] 2017-11-21 20:47
I'm closing this for now as I had gotten preliminary feedback that the proposed fix worked for the original problem -- but of course we can reopen it if there are any other issues on this architecture.

**Closed by gpertea** 2017-11-21 20:47 UTC
