### ISSUE TITLE
segmentation fault with long read data [ stringtie v2.1.4 ]

### ISSUE THREAD

**Issue by daniel-spies** [gpertea/stringtie#327] opened 2021-04-09 15:20 UTC
Hi there, thanks for the great tool. 

I'm creating guided transcriptome assemblies of 3 samples, two of which worked out perfectly, only one sample has some issues. Reads were aligned with deSALT.

I followed your "Extracting bundle data for debugging" guide and attached the files below. I also reproduced the error using only these files. Grateful for any help

[bundle_c5.zip](https://github.com/gpertea/stringtie/files/6286715/bundle_c5.zip)

run command: 

stringtie bundle_c5.bam \
        -G bundle_c5.gtf \
        -o stringtie2_gencode_all.gtf \
        -l STRG_${sample} \
        -L \
        -A geneAbundance.tab \
        -C covered_refTranscripts.gtf \
        -b refTranscripts \
        -v 2> run.log

**Comment by gpertea** [comment] 2021-04-09 15:54
This seems to be caused by a bug that was fixed in the latest v2.1.5 release -- I just tested your data with the current version and the bundle is processed successfully (while stringtie v2.1.4 crashes on it).  Since there was a slight adjustment to the coverage estimation values, I strongly suggest re-running all samples with v2.1.5.

**Closed by gpertea** 2021-04-09 15:54 UTC

**Comment by daniel-spies** [comment] 2021-04-09 15:57
I’ll do exactly that then.

Thanks for the ultrafast reply!

cheers
Daniel
