### ISSUE TITLE
Segmentation fault using StringTie2 prebuilt

### ISSUE THREAD

**Issue by smallfade** [gpertea/stringtie#231] opened 2019-08-06 06:34 UTC
I got the segmentation fault with different samples and looks like it happens randomly. It would work after several reruns. I think it may be something to do with the computing resource, because it works fine when the bam files are all smaller than 1GB. Is there any computing resource reference or benchmark for configuring the server to run it more stably?

**Comment by gpertea** [comment] 2019-09-06 02:07
I just discovered today that the prebuilt Linux binary may actually have an intrinsic defect when run on newer Linux systems, where it can exhibit an erratic, faulty behavior (hanging or crashes) on large input files.  I did build that on a VM with a very old Linux distribution: Red Hat 5 (CentOS 5), as I wanted to ensure maximum compatibility -- and now I see how that plan has backfired.
I just updated the latest v2.0.2b release with a Linux binary built on a CentOS 7 server and that seems to work well even on newer/other Linux distributions. 

If you are still looking for a resolution to this problem, could you please try this new prebuilt version and check that it works well for you on larger files? You can download the latest prebuilt files from https://github.com/gpertea/stringtie/releases or http://ccb.jhu.edu/software/stringtie/#install

**Comment by smallfade** [comment] 2019-09-07 05:50
> I just discovered today that the prebuilt Linux binary may actually have an intrinsic defect when run on newer Linux systems, where it can exhibit an erratic, faulty behavior (hanging or crashes) on large input files. I did build that on a VM with a very old Linux distribution: Red Hat 5 (CentOS 5), as I wanted to ensure maximum compatibility -- and now I see how that plan has backfired.
> I just updated the latest v2.0.2b release with a Linux binary built on a CentOS 7 server and that seems to work well even on newer/other Linux distributions.
> 
> If you are still looking for a resolution to this problem, could you please try this new prebuilt version and check that it works well for you on larger files? You can download the latest prebuilt files from https://github.com/gpertea/stringtie/releases or http://ccb.jhu.edu/software/stringtie/#install

Great! Thank you. Btw, I was running the pre-built on Ubuntu 18.04.2, will test the latest version soon.

**Comment by mpertea** [comment] 2019-09-07 13:24
Unfortunately meanwhile I got some reports that even that binary may have some similar issues (though I couldn't reproduce that myself yet) -- which seems to suggest that the way I statically link that executable may somehow introduce these issues (because the program compiled from source "normally" - i.e. without static linking - does not exhibit these problems). I am going to pin this issue until I figure out a better way to create that portable statically linked executable..

**Comment by gpertea** [comment] 2019-09-07 13:25
Unfortunately meanwhile I got some reports that even that binary may have some similar issues (though I couldn't reproduce that myself yet) -- which seems to suggest that the way I statically link that executable may somehow introduce these issues (because the program compiled from source "normally" - i.e. without static linking - does not exhibit these problems). I am going to pin this issue until I figure out a better way to create that portable statically linked executable..

**Comment by gpertea** [comment] 2019-09-09 16:26
Version 2.0.3, just released, added a couple of fixes and also used a slightly different recipe for building the Linux binary, which seems to work OK now on various platforms (built/tested on CentOS 7, but also successfully tested on Linux Mint 18, Debian 10 and a recently updated Arch Linux). 
Closing this for now, but feel free to report back if you notice any problems with this latest build.

**Closed by gpertea** 2019-09-09 16:26 UTC

**Comment by smallfade** [comment] 2019-09-11 02:28
Tried v2.0.3 on Ubuntu18.04.2, working well. Thanks.
