### ISSUE TITLE
Non-overlapping transcripts assigned with identical gene_id

### ISSUE THREAD

**Issue by hsinyenwu** [gpertea/stringtie#180] opened 2018-06-08 20:25 UTC
Hi,

I used stringtie to perform de novo transcriptome assembly for a non-model organism. I found that in some cases, identical gene_ids were given for separated transcripts:

For example (exon rows were removed) The first transcript does not overlap with the 2nd and 3rd transcripts, but they got the same gene_id:
```
2	StringTie	transcript	39370595	39379054	1000	-	.	gene_id "STRG.3229"; transcript_id "STRG.3229.1"; cov "1239.441406"; FPKM "26.293577"; TPM "32.687618";
2	StringTie	transcript	39381994	39385885	1000	-	.	gene_id "STRG.3229"; transcript_id "STRG.3229.2"; cov "89.505119"; FPKM "1.898767"; TPM "2.360506";
2	StringTie	transcript	39385314	39385885	1000	-	.	gene_id "STRG.3229"; transcript_id "STRG.3229.3"; cov "33.518940"; FPKM "0.711073"; TPM "0.883990";
```

Is there any option that I could use to avoid this issue? Thanks!

**Comment by gpertea** [comment] 2018-06-12 00:36
It is difficult to handle such noisy alignments, and it looks like StringTie got quite confused by all those overlapping alignments, as I see no transcripts produced in the middle region there in the 2nd screenshot, where we see the highest coverage peaks?

As a side/cautionary note, I see your BAM file has "merged" in its name, I hope that is not because you actually merged/multiplexed alignments from multiple samples there? Because that would be something we strongly argue _against_, as merging multiple samples amplifies the noise and breaks some core assumptions necessary for the application of the network flow algorithm used by StringTie in order to determine ("assemble") the expressed transcripts from read alignments.. And that would very likely be the cause of the issue reported here.

**Comment by hsinyenwu** [comment] 2018-06-12 20:58
Thanks, Geo!!! The merged means I merged the bam from 3 biological replicates before performing stringtie de novo assembly. I probably should do stringtie de novo with each bam file and merge with "stringtie merge", correct?

**Closed** 2018-06-29 23:19 UTC
