### ISSUE TITLE
Stringtie - Error: invalid genomic sequence data

### ISSUE THREAD

**Issue by chainorato** [gpertea/stringtie#143] opened 2017-09-26 05:04 UTC
Dear Stringtie's developer,

I tried to run Stringtie by this command:

stringtie <bam_file> -p 10 -G <annotation_file.gff> -o <output.gtf>

Some files have no problem, but some files have error messages such as:

Error: invalid genomic sequence data (NT_166466.1)!
Error: invalid genomic sequence data (NW_001867721.1)!
Error: invalid genomic sequence data (NW_003315959.1)!

Then, the output file couldn't be finished and a tmp.(something) files were left on the output directories.

Because I'm very new for computation, I can't understand from the code why this error appears. But I think this problem occurs to these nucleotide sequences. Please tell me how to check my file or how to solve this problem, TY.

**Comment by gpertea** [comment] 2017-09-27 16:39
The error suggests there are some entries in the *<annotation_file.gff>* which are not properly understood by Stringtie's GFF parser. Could you please send me the resulting `t.gff.gz` file you can obtain from a command like this:
```
fgrep NT_166466.1 annotation_file.gff | gzip -c - > t.gff.gz
```
.. of course replacing *annotation_file.gff* with the actual file name you used when you got the error reported above. What is the origin of that  annotation file (perhaps I can download it myself from a public source?). Also, please makes sure you are using the most recent (current) version of StringTie -- I can only help if I can reproduce the issue with the current version.

**Comment by chainorato** [comment] 2017-10-02 02:15
Thank you very much for your reply, here is a file you want,

[t.gff.gz](https://github.com/gpertea/stringtie/files/1347742/t.gff.gz)

and here is a link of annotation file, the origin comes from RefSeq database

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/635/GCF_000001635.25_GRCm38.p5/GCF_000001635.25_GRCm38.p5_genomic.gff.gz

FYI: My StringTie version is 1.3.3b. I found that StringTie could be run and it gave results when I add exclusion option (-x) followed by problem sequences.

**Comment by andrewstephenmason** [comment] 2017-11-23 15:57
Was a solution to this ever found?
I'm having a similar problem (admittedly with v1.3.1c) with the human annotation, including NW_003315959.1 as stated in the original question.
The GFF is correctly sorted and there don't appear to be any special characters on the offending lines.
Any thoughts?

**Comment by chainorato** [comment] 2017-11-23 16:06
I still didn't get it. Because most of the problematic sequences are unplaced in the chromosomes, so I decided to exclude problematic sequences at first by using the option provided in StringTie. 

-x <seqid_list>

**Comment by gpertea** [comment] 2017-11-23 16:13
That seems to be a problem with the GFF parsing code that should have been fixed by commit ecd2e7db521de326c2f46a54e2a7a5609deef8db
Haven't released that 1.3.4 version officially but building stringtie from the master branch should hopefully get rid of this error.

**Comment by chainorato** [comment] 2017-11-23 16:18
Thank you for your hard work. :)

**Comment by gpertea** [comment] 2017-11-23 16:31
@chainorato, I am sorry I forgot to thank you for that t.gff.gz file you sent earlier, it was actually very useful as a quick debug case in order to fix this error. My apologies for not getting back to you (and this issue) after that very rushed commit (which should have referenced this issue).

**Closed by gpertea** 2017-11-23 16:31 UTC
