### ISSUE TITLE
infinite loop?

### ISSUE THREAD

**Issue by kevlim83** [gpertea/stringtie#91] opened 2017-01-25 00:23 UTC
Hi,

I have been using stringtie for the past year with some success to de novo assemble a plant transcriptome. However, lately there is one sample that seems to be running forever. The other samples in the same batch completed with no problems. 

I tried to search around for clues but couldnt find any. The mapping rate seems ok, although there were a bit more multi-mappers for this specific sample as compared to other samples. Any ideas how I could resolve this issue?

Thanks.

**Comment by gpertea** [comment] 2017-01-25 02:00
I guess it is not impossible for the data in that sample to have generated some strange graph configuration that we haven't expected and, as the title suggested, an infinite loop might have been triggered there.. Since we just released the 1.3.2 version today and there were some internal changes that *might* have affected (prevented) rare situations like these, could you give this new version a try on that sample? 
If that doesn't resolve it we would definitely like to take a look at those sample data.  If you run stringtie with a single thread (no `-p` option) and with the `-v` option, the program should show at stderr what is the region (bundle location) where it gets stuck -- so then using `samtools view -b` you could extract the alignments from that region and share it with us to investigate how that happens.

**Comment by kevlim83** [comment] 2017-01-25 05:44
Hi,

Thanks for the reply. I did as you requested and here are the lines from
samtools (there were only few lines):

HWI-ST840:509:HYL5KADXX:1:2204:7129:81085 99 000080F_pilon 205660 50 101M =
205763 203
CGAAAGAGCACCGCACATCACGTGGTGTCTGGTGTGCCCCCAGTGGCCCCTAAAAATTTGAAGGACCGAGTGTCGTCCATGCTCGATTGTATTTATAATTG
@@@@BDDDFHDHFGIDHIDFE@EG
??@FECGEHGFGGGEEEGG=CGIIIEHECHFHHEEEEEBCCCC?;=8<:>8?B?BCCCCCBBCCB>CDEEDEC::C>
AS:i:-5 XN:i:0 XM:i:1 XO:i:0XG:i:0 NM:i:1 MD:Z:62A38 YT:Z:UU NH:i:1
HWI-ST840:509:HYL5KADXX:1:2204:7129:81085 147 000080F_pilon 205763 50
81M1I19M = 205660-203
TCAGGTCTCCAAGGTGAATAGCCTCTGGTCGATAGAACAATGTAGGCAAGGGAAGTCGACAAAATGGATCTGTAACCTCAGAAAAAAAGATTGGCTTTAAG
9DC?BA<:DCDDDCDEDDDDDDDDBBDDFDFDDFHHHHEHEGIIIIGJJJIJJIHGIJIJJJIGGJJIFIIGHIGGEGJJJJJJJJJIHHHDGFFFDD@
@@ AS:i:-14 XN:i:0XM:i:1 XO:i:1 XG:i:1 NM:i:2 MD:Z:69T30 YT:Z:UU NH:i:1
kevin@juggernaut:/fs/durio/wts/02_ALIGNMENT/tophat_out/d1_falcon_pilon_TN1506R0333$
samtools view accepted_hits.bam 000080F_pilon:205660-205862
HWI-ST840:509:HYL5KADXX:1:2204:7129:81085 99 000080F_pilon 205660 50 101M =
205763 203
CGAAAGAGCACCGCACATCACGTGGTGTCTGGTGTGCCCCCAGTGGCCCCTAAAAATTTGAAGGACCGAGTGTCGTCCATGCTCGATTGTATTTATAATTG
@@@@BDDDFHDHFGIDHIDFE@EG
??@FECGEHGFGGGEEEGG=CGIIIEHECHFHHEEEEEBCCCC?;=8<:>8?B?BCCCCCBBCCB>CDEEDEC::C>
AS:i:-5 XN:i:0 XM:i:1 XO:i:0XG:i:0 NM:i:1 MD:Z:62A38 YT:Z:UU NH:i:1
HWI-ST840:509:HYL5KADXX:1:2204:7129:81085 147 000080F_pilon 205763 50
81M1I19M = 205660-203
TCAGGTCTCCAAGGTGAATAGCCTCTGGTCGATAGAACAATGTAGGCAAGGGAAGTCGACAAAATGGATCTGTAACCTCAGAAAAAAAGATTGGCTTTAAG
9DC?BA<:DCDDDCDEDDDDDDDDBBDDFDFDDFHHHHEHEGIIIIGJJJIJJIHGIJIJJJIGGJJIFIIGHIGGEGJJJJJJJJJIHHHDGFFFDD@
@@ AS:i:-14 XN:i:0XM:i:1 XO:i:1 XG:i:1 NM:i:2 MD:Z:69T30 YT:Z:UU NH:i:1

Please let me know if you found out the problem.

Thanks.

Regards,
Kevin
ᐧ

**Comment by gpertea** [comment] 2017-01-25 13:16
That's not a good way to share SAM alignments, some information might get lost when you simply copy and paste text like this in a web post. I meant to get a binary bam file (samtools view `-b` ...), which also has some header information I might need, after indexing your bam file of course (samtools index) and also please provide me with the stringtie command line you used and possibly the reference annotation that you used (if you did use one in that command line). You should either attach the .bam file and the annotation file to the posts here (which might not work for larger files) or e-mail them to me as attachments (or use a file sharing service if you prefer).  Of course the command line could be posted right here (and it is a good idea to put that and the stringtie version in the first post when you have a bug report).

Also, you haven't answered my other question -- should I assume that this happened with stringtie v1.3.2 version we just released?

**Comment by kevlim83** [comment] 2017-01-26 01:49
Sorry for the confusion. We used v1.3.2 initially and subsequently v1.3.2b which was released two days ago as advised by you.

We are using stringtie with default parameters, the command line is something like this: stringtie .../tophat_dir/accepted_hits.bam -o results.gtf

As we are studying a new species, we do not have reference annotation. I have attached the files here. Please let us know. Thanks very much for your help.

[debug.zip](https://github.com/gpertea/stringtie/files/731385/debug.zip)

**Comment by gpertea** [comment] 2017-01-26 15:10
Can you actually reproduce this problem on your side when you run stringtie on this small .bam file you sent me?
Because I can't see any problem here, this is what I get:
```
$ stringtie -v -o out.gtf debug.bam
Command line was:
../stringtie -v -o out.gtf debug.bam
Default stack size for threads: 8388608
[01/26 10:09:02]>bundle 000080F_pilon:205660-205862(2) (0 guides) loaded, begins processing...
[01/26 10:09:02]^bundle 000080F_pilon:205660-205862(2) done (0 processed potential transcripts).
[01/26 10:09:02] All threads finished.
Total count of aligned fragments: 2
Fragment coverage length: 100.5
```
What is the output that you get when you run the same command on this small debug.bam file?

**Comment by gpertea** [comment] 2017-01-26 21:37
Thinking more about this, it's possible that stringtie gets stuck trying to read the *next* bundle, if there is something strange in that `accepted_hits.bam` file (corrupted or otherwise unusual). It would be interesting to take a look -- perhaps you could share the whole accepted_hits.bam file in this case. If you cannot put it on a file sharing service drop me an e-mail at gpertea@jhu.edu and I can send instructions for ftp upload to our server here.
You could also try to load that `accepted_hits.bam` in IGV to visually check if there is anything unusual following this very small region (000080F_pilon:205660-205862).

**Comment by gpertea** [comment] 2017-02-09 14:19
I am closing this for now for lack of follow up by the OP -- but please,  kevlim83 if you are getting this and still have that issue I'd be glad to re-open the investigation.

**Closed by gpertea** 2017-02-09 14:19 UTC
