### ISSUE TITLE
Error at GBitVec: index out of bounds (Stringtie version 1.2.2)

### ISSUE THREAD

**Issue by tylim** [gpertea/stringtie#45] opened 2016-04-18 16:38 UTC
Hi,

This issue has been reported and closed in [#26](https://github.com/gpertea/stringtie/issues/26) and [#32](https://github.com/gpertea/stringtie/issues/32), but we are currently still running into the same error with Stringtie version 1.2.2.

> [04/18 16:52:28]>bundle ST4.03ch09:61229862-61324206(2719458) (0 guides) loaded, begins processing...
[04/18 16:52:28]Error at GBitVec: index 480460105 out of bounds (size 480460105)

The BAM file was generated with Hisat version 2.0.1-beta with the `--dta` and  `--rna-strandness` options. We then run Stringtie (using ~16Gb of RAM) with the following command:
`$stringtie $sample.bam -p $threads -o $sample.gtf `

I've extracted the regions affected (ST4.03ch09:61229862-61324206) into a smaller [BAM file](https://drive.google.com/folderview?id=0BxWAxrVTZj0IVkNrd1FReF80Ukk&usp=sharing) for your reference.

Cheers.

**Comment by gpertea** [comment] 2016-04-18 17:04
Thank you for providing the BAM file -- that was very helpful, I was able to reproduce the error. We're now investigating this issue.

**Comment by tylim** [comment] 2016-04-19 11:15
That's great! Thanks very much.

**Comment by mpertea** [comment] 2016-04-21 20:32
We identified the problem and fixed it. The next version of StringTie (1.2.3) with the fix will be released next week. Thank you for pointing it out!

**Comment by iandriver** [comment] 2016-04-29 19:02
Kind of stuck waiting for this update. Re-ran after running make on the latest git, but still received this error:
`Error at GBitVec: index 362979864 out of bounds (size 362979863)`
bam file was generated with the latest Hisat2.
Seems like the problem has been diagnosed but hasn't been committed yet? Happy to wait for the release, but will send more info on my error if this is still happening.

**Comment by gpertea** [comment] 2016-04-29 19:16
sorry, the main developer (Mihaela Pertea) hasn't pushed the fix to github yet as there're still a few minor details to iron out around it -- nothing very complicated, but things got also delayed due to an annoying cold/flu that she caught these days..

**Comment by gpertea** [comment] 2016-05-11 22:47
This should be fixed now in both master and devel branches, though during the interactive git rebase operation (my bad) the comment describing the fix was missed.

**Comment by gpertea** [comment] 2016-05-16 16:18
v1.2.3 was officially released and we believe this bug was fixed.

**Closed by gpertea** 2016-05-16 16:18 UTC
Labels: bug

**Comment by tylim** [comment] 2016-05-17 12:18
Hi @gpertea  and @mpertea, we can now confirm that the new Stringtie v1.2.3 job completed without an error.  Thanks very much for both of your help!

Cheers.
