### ISSUE TITLE
Segmentation fault with annotation file

### ISSUE THREAD

**Issue by PeterVenhuizen** [gpertea/stringtie#3] opened 2015-03-17 10:45 UTC
Hi, I'm trying to run stringtie (v1.0.2) with a annotation gff file, but every time I run it, it throws a segmentation fault (core dumped) and quits. Without the annotation gff file stringtie seems to run fine. Is this a bug, or might there be something wrong with my annotation file?

I want to compare the stringtie output with cufflinks and because I run cufflinks with annotation, I want to run stringtie with an annotation file as well. 

Thanks,
Peter

**Comment by gpertea** [comment] 2015-03-17 11:36
Thanks for reporting this, it looks like a bug (especially if the same file works with cufflinks) -- the gff parser is probably choking on something there.. is there any way to point me to the annotation gff which triggers this bug?

**Comment by PeterVenhuizen** [comment] 2015-03-17 11:47
The gff file can be downloaded from the arabidopsis.org FTP server. The file is located here => ftp://ftp.arabidopsis.org/home/tair/Genes/TAIR10_genome_release/TAIR10_gff3/ and the file is called TAIR10_GFF3_genes.gff

**Comment by PeterVenhuizen** [comment] 2015-03-17 13:14
OK, I have found out something more about the gff file I used, which is slightly different from the one on the FTP server. The chromosomes in my gff file are annotated as 1, 2, 3, 4, 5, Mt and Pt, whereas the ones in the FTP gff file are given as Chr1, Chr2, Chr3, etc. When I used the gff file with the chromosomes with the Chr-prefix than stringtie runs without problems, so maybe this prefix is required in stringtie and needs to be present?

**Comment by gpertea** [comment] 2015-03-17 14:18
Well, a segmentation fault still indicates at least a usability bug which I should fix, but please make sure that the chromosome names in the annotation file match the ones in the alignment .bam file (which are the names of the chromosomes/scaffolds of the target genome). This has been also the case with TopHat and Cufflinks and it is a basic requirement when using annotation data with these programs - always make sure that the genome sequences (on which the reads were mapped) and the annotation file both use the same naming convention for the chromosomes.

**Comment by PeterVenhuizen** [comment] 2015-03-17 15:23
This is of course something I've done. It's just that I was surprised that stringtie worked with a slightly different annotation file and not with the one I used for the TopHat mapping.

**Comment by gpertea** [comment] 2015-04-04 02:32
I am not able to reproduce the crash - perhaps I could take another look if you point me to the exact same file that was used with Stringtie when it crashed (since you said that it wasn't exactly the one from the FTP site).

**Comment by PeterVenhuizen** [comment] 2015-04-08 10:20
The GFF file I used can be downloaded from here -> https://www.dropbox.com/s/iq8aec5dftx8eyj/TAIR10_GFF3_genes.gff?dl=0

**Comment by PeterVenhuizen** [comment] 2015-04-09 10:03
I don't know if the following is relevant information, but the segmentation fault (core dumped) error occurs at the exact same point every time. The temporary output file can be downloaded from here -> https://www.dropbox.com/s/6yv5cnaa71o3ixm/transcripts.gtf.tmp?dl=0

**Comment by gpertea** [comment] 2015-04-09 10:16
Thank you for providing us with the GFF file you used earlier, and for this partial output of StringTie before the crash. About this crash which happens at the exact same point on your data, can you confirm that it happens even with the latest version of StringTie, v1.0.3 ?

**Comment by PeterVenhuizen** [comment] 2015-04-09 10:53
Yes, the transcripts.gtf.tmp file is generated by stringtie v1.0.3

**Comment by gpertea** [comment] 2015-04-09 12:16
Since some partial output is being generated, it means that is really the combination between guides (annotation) and the read alignments that triggers a bug there in StringTie. Could you run StringTie on the same data with only 1 cpu (so no -p option) and with -v option, and let me know the last few lines there are printed to stderr? That should show you a chromosome location where a bundle is causing the crash (the partial output file is not that precise about that). Then once we pinpoint that region,  I would like to look at the read alignments in that region - if you can share that part of the .BAM file please write to me at gpertea@jhu.edu directly and I'll give you instructions how to extract and upload those alignments to our ftp site (or, if the file is not too big, you can perhaps share that through dropbox if you have the space).

**Comment by gpertea** [comment] 2015-05-17 16:15
Sorry for the late update - I finally got around to fixing this, it was a silly issue caused by transcripts with a feature name "mRNA_TE_gene" in that TAIR10 annotation file which confused the parser into assuming those are gene entries instead of transcripts (frankly I still think the proper syntax should have been "TE_gene_mRNA"). The fix is in the v1.0.4 release which should be out there in the next few days (or you can get it now from the 'devel' branch here on github).

**Closed** 2015-10-20 15:37 UTC
Labels: bug
